browser.theme.update({
	'colors': {
		'accentcolor': '#fff',
		'button_background_active': '#ccc',
		'button_background_hover': '#ddd',
//	'icons': '#000',
	'icons_attention': '#06c',
//	'popup': '#fff',
		'popup_border': '#ccc',
		'popup_highlight': '#eee',
//	'popup_highlight_text': '#000',
//	'popup_text': '#000',
		'tab_background_separator': '#ccc',
		'tab_line': '#eee',
	'tab_loading': '#06c',
		'tab_selected': '#eee',
//	'tab_text': '#f0f',
		'textcolor': '#000',
		'toolbar': '#eee',
		'toolbar_bottom_separator': '#ccc',
		'toolbar_field': '#fff',
		'toolbar_field_border': '#ccc',
	'toolbar_field_border_focus': '#06c',
//	'toolbar_field_focus': '#fff',
		'toolbar_field_separator': '#ccc',
//	'toolbar_field_text': '#000',
//	'toolbar_field_text_focus': '#000',
//	'toolbar_text': '#000',
		'toolbar_top_separator': '#ccc',
		'toolbar_vertical_separator': '#ccc',
	},
})
